<a href="https://colab.research.google.com/github/Ammulator/Logistic-Regression-using-sklearn/blob/main/Logistic_Regression_with_Sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [ ]:
import pandas as pd
import numpy as np

Importing the file in Colab with the given data set

In [ ]:
df=pd.read_csv("sample_data/california_housing_train.csv")
df.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

Prep Data with Pandas

In [ ]:
#As the above data is in Integer format then we didn't want to convert String to Integer
#Now we take the Features and create a Numpy Array X
#First we select all the columns we are intersted and then covert it into numpy arrays using values.
#Here we are using the first 20 Values only
X=df[['housing_median_age','total_rooms','total_bedrooms','households','median_income','population']].values[:20]

In [ ]:
#Now lets take the target or the predict column on Y and convert it into numpy arrays using values.
Y=df['median_house_value'].values[:20]

In [ ]:
print(X)
print("\n\n\n")
print(Y)

[[1.5000e+01 5.6120e+03 1.2830e+03 4.7200e+02 1.4936e+00 1.0150e+03]
 [1.9000e+01 7.6500e+03 1.9010e+03 4.6300e+02 1.8200e+00 1.1290e+03]
 [1.7000e+01 7.2000e+02 1.7400e+02 1.1700e+02 1.6509e+00 3.3300e+02]
 [1.4000e+01 1.5010e+03 3.3700e+02 2.2600e+02 3.1917e+00 5.1500e+02]
 [2.0000e+01 1.4540e+03 3.2600e+02 2.6200e+02 1.9250e+00 6.2400e+02]
 [2.9000e+01 1.3870e+03 2.3600e+02 2.3900e+02 3.3438e+00 6.7100e+02]
 [2.5000e+01 2.9070e+03 6.8000e+02 6.3300e+02 2.6768e+00 1.8410e+03]
 [4.1000e+01 8.1200e+02 1.6800e+02 1.5800e+02 1.7083e+00 3.7500e+02]
 [3.4000e+01 4.7890e+03 1.1750e+03 1.0560e+03 2.1782e+00 3.1340e+03]
 [4.6000e+01 1.4970e+03 3.0900e+02 2.7100e+02 2.1908e+00 7.8700e+02]
 [1.6000e+01 3.7410e+03 8.0100e+02 8.2400e+02 2.6797e+00 2.4340e+03]
 [2.1000e+01 1.9880e+03 4.8300e+02 4.3700e+02 1.6250e+00 1.1820e+03]
 [4.8000e+01 1.2910e+03 2.4800e+02 2.1100e+02 2.1571e+00 5.8000e+02]
 [3.1000e+01 2.4780e+03 4.6400e+02 4.7900e+02 3.2120e+00 1.3460e+03]
 [1.5000e+01 1.4480e+03 3.7800e+02

***Build a Logistic regression Model***

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X,Y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#Now we predict the value
print(model.predict(X[:5]))
print("\n\n")
print(model.predict(X))
print("\n\n")
print(Y)

[66900. 80100. 85700. 73400. 65500.]



[66900. 80100. 85700. 73400. 65500. 74000. 82400. 48500. 58400. 48100.
 86500. 62000. 48600. 70400. 45000. 69100. 94900. 25000. 44000. 27500.]



[66900. 80100. 85700. 73400. 65500. 74000. 82400. 48500. 58400. 48100.
 86500. 62000. 48600. 70400. 45000. 69100. 94900. 25000. 44000. 27500.]


**Score the Model to Calculate the Accuracy Score**

In [ ]:
y_pre=model.predict(X)
Y==y_pre

print((Y==y_pre).sum())
#We can see that out of 20 data points all are correct ao to calculate the accuracy score 
#we divide the sum with the shape
print((Y==y_pre).sum()/Y.shape[0])
#Thus we get the accuracy as 100 percent
#We can also calculate the accuracy score using the score method 
print("The accuracy score is : ",model.score(X,Y))

20
1.0
The accuracy score is :  1.0
